-- ========================================
-- DJ System - Supabase Migration Script
-- Magic Link Authentication Tokens
-- ========================================
-- Run this in Supabase SQL Editor

-- 1. Create Magic Link Tokens Table
CREATE TABLE IF NOT EXISTS "magic_link_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token_id" VARCHAR(255) NOT NULL UNIQUE,
    "user_id" BIGINT NOT NULL,
    "target_url" VARCHAR(500) NOT NULL,
    "action" VARCHAR(50) NOT NULL,
    "metadata" TEXT,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "used" BOOLEAN NOT NULL DEFAULT false,
    "used_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create Indexes for Performance
CREATE INDEX IF NOT EXISTS "magic_link_tokens_user_id_idx" ON "magic_link_tokens"("user_id");
CREATE INDEX IF NOT EXISTS "magic_link_tokens_token_id_idx" ON "magic_link_tokens"("token_id");
CREATE INDEX IF NOT EXISTS "magic_link_tokens_expires_at_idx" ON "magic_link_tokens"("expires_at");
CREATE INDEX IF NOT EXISTS "magic_link_tokens_used_idx" ON "magic_link_tokens"("used");

-- 3. Add Foreign Key Constraint
ALTER TABLE "magic_link_tokens" 
ADD CONSTRAINT "magic_link_tokens_user_id_fkey" 
FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 4. Add Table Comment
COMMENT ON TABLE "magic_link_tokens" IS 'Magic Link Authentication Tokens - One-time use tokens for email-based auto-login';

-- 5. Add Column Comments
COMMENT ON COLUMN "magic_link_tokens"."id" IS 'Primary key - auto-increment';
COMMENT ON COLUMN "magic_link_tokens"."token_id" IS 'Unique token identifier (JWT)';
COMMENT ON COLUMN "magic_link_tokens"."user_id" IS 'User who owns this token';
COMMENT ON COLUMN "magic_link_tokens"."target_url" IS 'URL to redirect after login';
COMMENT ON COLUMN "magic_link_tokens"."action" IS 'Action type (approve, reject, view, etc.)';
COMMENT ON COLUMN "magic_link_tokens"."metadata" IS 'Additional metadata (JSON string)';
COMMENT ON COLUMN "magic_link_tokens"."expires_at" IS 'Token expiry timestamp';
COMMENT ON COLUMN "magic_link_tokens"."used" IS 'Whether token has been used';
COMMENT ON COLUMN "magic_link_tokens"."used_at" IS 'Timestamp when token was used';
COMMENT ON COLUMN "magic_link_tokens"."created_at" IS 'Token creation timestamp';

-- 6. Enable Row Level Security (RLS) - Important for Supabase
ALTER TABLE "magic_link_tokens" ENABLE ROW LEVEL SECURITY;

-- 7. Create RLS Policies
-- Policy: Users can only see their own tokens
CREATE POLICY "Users can view own magic link tokens" ON "magic_link_tokens"
    FOR SELECT USING (auth.uid()::text = user_id::text);

-- Policy: Users can insert their own tokens
CREATE POLICY "Users can insert own magic link tokens" ON "magic_link_tokens"
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

-- Policy: Service role can manage all tokens (for backend operations)
CREATE POLICY "Service role can manage all tokens" ON "magic_link_tokens"
    FOR ALL USING (auth.role() = 'service_role');

-- 8. Create Cleanup Function (Optional - for automated cleanup)
CREATE OR REPLACE FUNCTION cleanup_expired_magic_links()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    -- Delete expired tokens
    DELETE FROM "magic_link_tokens" 
    WHERE "expires_at" < NOW() OR ("used" = true AND "used_at" < NOW() - INTERVAL '7 days');
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- 9. Grant Permissions
GRANT SELECT, INSERT, UPDATE ON "magic_link_tokens" TO authenticated;
GRANT SELECT, INSERT, UPDATE ON "magic_link_tokens" TO service_role;
GRANT EXECUTE ON FUNCTION cleanup_expired_magic_links() TO authenticated;
GRANT EXECUTE ON FUNCTION cleanup_expired_magic_links() TO service_role;

-- 10. Verify Table Creation
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'magic_link_tokens' 
AND table_schema = 'public'
ORDER BY ordinal_position;

-- ========================================
-- Migration Complete!
-- ========================================
-- Next Steps:
-- 1. Restart your backend server
-- 2. Test magic link generation and verification
-- 3. Check that tokens are being created in this table
-- ========================================
