-- ========================================
-- DJ System - Supabase Migration Script (Fixed)
-- Magic Link Authentication Tokens
-- ========================================
-- Run this in Supabase SQL Editor

-- 1. Drop existing table if exists (for clean migration)
DROP TABLE IF EXISTS "magic_link_tokens" CASCADE;

-- 2. Create Magic Link Tokens Table
CREATE TABLE "magic_link_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token_id" VARCHAR(255) NOT NULL UNIQUE,
    "user_id" BIGINT NOT NULL,
    "target_url" VARCHAR(500) NOT NULL,
    "action" VARCHAR(50) NOT NULL,
    "metadata" TEXT,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "used" BOOLEAN NOT NULL DEFAULT false,
    "used_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Indexes for Performance
CREATE INDEX "magic_link_tokens_user_id_idx" ON "magic_link_tokens"("user_id");
CREATE INDEX "magic_link_tokens_token_id_idx" ON "magic_link_tokens"("token_id");
CREATE INDEX "magic_link_tokens_expires_at_idx" ON "magic_link_tokens"("expires_at");
CREATE INDEX "magic_link_tokens_used_idx" ON "magic_link_tokens"("used");

-- 4. Add Foreign Key Constraint
ALTER TABLE "magic_link_tokens" 
ADD CONSTRAINT "magic_link_tokens_user_id_fkey" 
FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 5. Add Table Comment
COMMENT ON TABLE "magic_link_tokens" IS 'Magic Link Authentication Tokens - One-time use tokens for email-based auto-login';

-- 6. Enable Row Level Security (RLS) - Important for Supabase
ALTER TABLE "magic_link_tokens" ENABLE ROW LEVEL SECURITY;

-- 7. Create RLS Policies (Fixed for UUID vs BIGINT)
-- Policy: Service role can manage all tokens (for backend operations)
CREATE POLICY "Service role can manage all tokens" ON "magic_link_tokens"
    FOR ALL USING (auth.role() = 'service_role');

-- Note: We'll skip user-specific policies for now since backend uses service role

-- 8. Create Cleanup Function
CREATE OR REPLACE FUNCTION cleanup_expired_magic_links()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    -- Delete expired tokens
    DELETE FROM "magic_link_tokens" 
    WHERE "expires_at" < NOW() OR ("used" = true AND "used_at" < NOW() - INTERVAL '7 days');
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- 9. Grant Permissions
GRANT SELECT, INSERT, UPDATE ON "magic_link_tokens" TO authenticated;
GRANT SELECT, INSERT, UPDATE ON "magic_link_tokens" TO service_role;
GRANT EXECUTE ON FUNCTION cleanup_expired_magic_links() TO authenticated;
GRANT EXECUTE ON FUNCTION cleanup_expired_magic_links() TO service_role;

-- 10. Verify Table Creation
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'magic_link_tokens' 
AND table_schema = 'public'
ORDER BY ordinal_position;

-- 11. Test Insert (Optional - to verify table works)
-- You can run this after the migration to test:
-- INSERT INTO "magic_link_tokens" ("token_id", "user_id", "target_url", "action", "expires_at")
-- VALUES ('test-token-123', 1, '/jobs/1', 'view', NOW() + INTERVAL '24 hours');

-- ========================================
-- Migration Complete!
-- ========================================
-- Next Steps:
-- 1. Restart your backend server
-- 2. Test magic link generation and verification
-- 3. Check that tokens are being created in this table
-- ========================================
